import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header/header";
import { ToasterComponent } from "@/components/toaster/toaster";
import AuthContextProvider from "../helpers/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi Service",
  description: "Generated by Venture Buddy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider> 
          <main className="bg-slate-50 ">
          <ToasterComponent />
          <Header />
          <div className=" min-h-screen max-w-screen-xl m-auto p-4 ">
            {children}
          </div>
        </main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
